# Generated by Django 5.0.4 on 2024-05-04 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('title', models.CharField(primary_key=True, serialize=False, verbose_name='brand unique name')),
                ('desctiption', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('addres', models.TextField()),
                ('city', models.CharField()),
                ('point', models.JSONField()),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviewapi.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resorce', models.CharField()),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('date', models.DateField()),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviewapi.location')),
            ],
        ),
    ]
