# Generated by Django 5.0.4 on 2024-05-16 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapi', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('tel_city_code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Телефонный код города')),
                ('name', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='active_on_rank',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='active_on_rank',
            field=models.BooleanField(default=True),
        ),
        # migrations.AlterField(
        #     model_name='location',
        #     name='city',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviewapi.city'),
        # ),
    ]
