# Generated by Django 5.0.4 on 2024-05-16 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapi', '0003_city_brand_active_on_rank_location_active_on_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviewapi.city'),
        ),
    ]
